---
output:
  word_document: default
  pdf_document: default
  html_document: default
---
```{r setup, include=FALSE}
library(ggplot2)
library(dplyr)
library(tibble)
library(tidyr)
library(stringr)
library(tidytext)
library(topicmodels)
library(RColorBrewer)
library(wordcloud)
library(ggridges)
library(igraph)
library(ggraph)
library(sentimentr)
library(syuzhet)
library(broom)
library(urltools)
library(exploratory)
library(ldatuning)
library(purrr)
library(CTM)
library(stm)
library(corpus)
library(tm)
library(quanteda)
source("../libs/multiplot.R")
spooky<-read.csv('../data/spooky.csv',as.is=T)
```



##Step 2: data Processing

###1:Punctuation -- typical sentence structure.  Clauses they have.  Number of commas or semicolons.

```{r}
str_count(spooky,',')
str_count(spooky,';' )
```
Poe used commas 19578 times, Lovecraft used commas 57798 times, Shelly used commas 19578 times. Poe used semicolons 0 times, Lovecraft used semicolons 5159 times, Shelly used semicolons 0 times.

###2: He/she
```{r}
str_count(spooky,'He')
str_count(spooky,'he')
str_count(spooky,'She')
str_count(spooky,'she')
```
Poe and Shelly did not use he/she, Lovecraft used he more than she.